version = 1
name = "Snowden-Visual-Novel"

[setup]
script = ""

[[actions]]
name = "Run"
icon = "run"
command = '''
Get-Process -Name renpy -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Process -FilePath 'D:\богдан\_tools\renpy-8.5.2-sdk\renpy.exe' -ArgumentList @('D:\богдан\Snowden-Visual-Novel') -WorkingDirectory 'D:\богдан\_tools\renpy-8.5.2-sdk'
'''
